# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rbayz_cpp <- function(modelFrame, chain, silent) {
    .Call(`_BayzR_rbayz_cpp`, modelFrame, chain, silent)
}

