# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#' Core bayz C++ function call
#'
#' Fits a model based on the given modelframe, using Markovian Coalescens
#'
#' @param modelFrame Generated
#' @param chain      Three value vector containing the number of iterations c(1000,100,10)
#'
#' @return A fitted bayz model
#' @import Rcpp
#' @export


rbayz_cpp <- function(modelFrame, chain) {
    .Call('_BayzR_rbayz_cpp', PACKAGE = 'BayzR', modelFrame, chain)
}

